### ISSUE TITLE
make it compile on windows (update building doc)

### ISSUE THREAD

**Issue by agudpp** [agudpp/alias#111]
### TODOS:
- [x] We added the crossguid
- [x] We need to compile the qxtglobalshortcut in debug / release mode (and change the lib name, adding a d in the end). This should be fixed in a different way (supported directly from qtxglobalshortcut for example). Otherwise mixing debug and release libs crashes (also the .dll.a file needs to be created properly)
- [x] we need to set properly the file where we will install all the files, some of them needs to be added by hand (libstlc++... etc).
- [ ] installation of the profile and data in the users folder needs to be done manually, we need to make it automatically this.
